HOST: http://api.propzmedia.com/v1/

--- Propzmedia Studio v1 ---

---
Welcome to Propzmedia API v1 documentation. All comments can be written in (support [Markdown](http://daringfireball.net/projects/markdown/syntax) syntax)
---

--
Marketing Database Resources
The following is a section of resources related to Marketing Databases
--

Get Marketing Database
GET /databases/UUID
< 200
< Content-Type: application/json
{
  "url": "/databases/UUID",
  "name": "SocioMMA",
  "inChargeMgr": { "url": "/managers/UUID" },
  "dateCreated": "2012-07-01T14:22:20.029Z", // ISO 8601 Date string
  "dateUpdated": "2012-07-01T14:22:20.029Z" // ISO 8601 Date string
}

Create new Marketing Database
PUT /databases/UUID
> Content-Type: application/json
{
  "name": "SocioMMA",
  "inChargeMgr": { "url": "/managers/UUID" }
}
< 201
< Content-Type: application/json
{
  "url": "/databases/UUID"
  // ... other fields omitted for brevity
}

Update Marketing Database
POST /databases/UUID
> Content-Type: application/json
{
  "name": "SuccessoClub",
  "inChargeMgr": { // Optional
  "url": "/managers/UUID"
  }
}
< 200
< Content-Type: application/json
{
  "url": "/databases/UUID"
  // ... other fields omitted for brevity
}

Delete Marketing database
DELETE /databases/UUID
< 204



--
Credential Resources
The following is a section of resources related to Credentials
--

Get Credential
GET /credentials/UUID
< 200
< Content-Type: application/json
{
  "url": "/credentials/UUID",
  "apiKey": "UUID", // May be null if "targetMgr" present
  "targetMgr": { "url": "/managers/UUID" }, // May be null if "apiKey"/"apiSecret" present
  "targetMgrInvitation": { "url": "manager-invitations/UUID"} // Coupled with "targetMgr"
  "accessLevel": "ADMIN", // STAFF / ADMIN / WRITE / READ
  "active": true,
  "marketingDb": { "url": "/databases/UUID" },
  "type": "CONSOLE", // CONSOLE / WS
  "dateCreated": "2012-07-01T14:22:20.029Z", // ISO 8601 Date string
  "dateUpdated": "2012-07-01T14:22:20.029Z", // ISO 8601 Date string
  "validUntil": "2012-07-01T14:22:20.029Z" // ISO 8601 Date string
}

List Credentials for this Manager
GET /credentials
< 200
< Content-Type: application/json
{ 
  "url": "/credentials",
  "offset": 0,
  "limit": 50,
  "first": {"url": "/credentials?offset=0"},
  "prev": null,
  "next": {"url": "/credentials?offset=50"},
  "last": {"url": "/credentials?offset=100"},
  "items": [
{
  "url": "/credentials/UUID"
  // ... other fields omitted for brevity
}
] }

Create new Credential for given Marketing DB
PUT /credentials/UUID
> Content-Type: application/json
{
  "apiKey": "UUID", // Optional
  "apiSecret": "UUID", // Password to be encrypted. Optional
  "targetMgr": { "url": "/managers/UUID" }, // May be null if "apiKey"/"apiSecret" present
  "targetMgrInvitation": { "url": "manager-invitations/UUID"} // Coupled with "targetMgr"
  "accessLevel": "ADMIN", // STAFF / ADMIN / WRITE / READ
  "active": true,
  "marketingDb": { "url": "/databases/UUID" },
  "type": "CONSOLE", // CONSOLE / WS
  "validUntil": "2012-07-01T14:22:20.029Z" // ISO 8601 Date string
}
< 201
< Content-Type: application/json
{
  "url": "/credentials/UUID"
  // ... other fields omitted for brevity
}

Update Credential
POST /credentials/UUID
> Content-Type: application/json
{
  "apiSecret": "UUID", // Password to be encrypted. Optional
  "accessLevel": "WRITE", // STAFF / ADMIN / WRITE / READ
  "active": false,
  "type": "WS", // CONSOLE / WS
  "validUntil": "2012-07-01T14:22:20.029Z" // ISO 8601 Date string
}
< 200
< Content-Type: application/json
{
  "url": "/credentials/UUID"
  // ... other fields omitted for brevity
}

Delete credentialb
DELETE /credentials/UUID
< 204



--
Manager Resources
The following is a section of resources related to Managers
--

Get Manager
GET /managers/UUID
< 200
< Content-Type: application/json
{
  "url": "/managers/UUID",
  "username": "john", 
  "firstName": "John",
  "lastName": "Smith",
  "dateCreated": "2012-07-01T14:22:20.029Z", // ISO 8601 Date string
  "dateUpdated": "2012-07-01T14:22:20.029Z" // ISO 8601 Date string
}

Create new Manager. This function is used by SignUp module only.
PUT /managers/UUID
> Content-Type: application/json
{
  "username": "john", 
  "firstName": "John",
  "lastName": "Smith",
  "password": "UUID", // Password to be encrypted. Optional
}
< 201
< Content-Type: application/json
{
  "url": "/managers/UUID"
  // ... other fields omitted for brevity
}

Update Manager
POST /managers/UUID
> Content-Type: application/json
{
  "firstName": "Mark",
  "lastName": "Twain",
  "password": "UUID", // Password to be encrypted. Optional
}
< 200
< Content-Type: application/json
{
  "url": "/managers/UUID"
  // ... other fields omitted for brevity
}



--
Manager Invitation Resources
The following is a section of resources related to Manager Invitations
--

Get Manager Invitation
GET /manager-invitations/UUID
< 200
< Content-Type: application/json
{
  "url": "/manager-invitations/UUID",
  "email": "john@gmail.com",
  "active": true,
  "sendStatus": "SENT", // NOT_SENT / SENT / FAILURE
  "targetMgr": null, // If null - invitation has not been utilized
  "dateCreated": "2012-07-01T14:22:20.029Z", // ISO 8601 Date string
  "dateUpdated": "2012-07-01T14:22:20.029Z", // ISO 8601 Date string
  "validUntil": "2012-07-01T14:22:20.029Z" // ISO 8601 Date string
}

List Manager Invitation created by this Manager
GET /manager-invitations
< 200
< Content-Type: application/json
{
  "url": "/manager-invitations",
  "offset": 0,
  "limit": 50,
  "first": {"url": "/manager-invitations?offset=0"},
  "prev": null,
  "next": {"url": "/manager-invitations?offset=50"},
  "last": {"url": "/manager-invitations?offset=100"},
  "items": [
{
  "url": "/manager-invitations/UUID"
  // ... other fields omitted for brevity
}
]}

Create new Manager Invitation
PUT /manager-invitations/UUID
> Content-Type: application/json
{
  "email": "john@gmail.com"
}
< 201
< Content-Type: application/json
{
  "url": "/manager-invitations/UUID"
  // ... other fields omitted for brevity
}

Update Manager Invitation
POST /manager-invitations/UUID
> Content-Type: application/json
{
  "active": false,
  "validUntil": "2012-07-01T14:22:20.029Z" // ISO 8601 Date string
}
< 200
< Content-Type: application/json
{
  "url": "/manager-invitations/UUID"
  // ... other fields omitted for brevity
}


--
Segment Resources
The following is a section of resources related to Segments
--

Get Segment
GET /segments/UUID
< 200
< Content-Type: application/json
{
  "url": "/segments/UUID",
  "name": "Segment 1",
  "query": "some query",
  "rebuildFrequency": "DAILY", // HOURLY / DAILY / WEEKLY / MONTHLY
  "marketingDb": { "url": "/databases/UUID" },
  "segmentMembership": { "url": "/segment-memberships?segment=UUID" },
  "dateCreated": "2012-07-01T14:22:20.029Z", // ISO 8601 Date string
  "dateUpdated": "2012-07-01T14:22:20.029Z" // ISO 8601 Date string
}

List Segment for specific Marketing DB
GET /segments?database=UUID
< 200
< Content-Type: application/json
{
  "url": "segments?database=UUID",
  "offset": 0,
  "limit": 50,
  "first": {"url": "/segments?database=UUID&offset=0"},
  "prev": null,
  "next": {"url": "/segments?database=UUID&offset=50"},
  "last": {"url": "/segments?database=UUID&offset=100"},
  "items": [
{
  "url": "/manager-invitations/UUID"
  // ... other fields omitted for brevity
}
]}

Create new Segment
PUT /segments/UUID
> Content-Type: application/json
{
  "name": "Segment 1",
  "query": "some query",
  "rebuildFrequency": "DAILY", // HOURLY / DAILY / WEEKLY / MONTHLY
  "marketingDb": { "url": "/databases/UUID" }
}
< 201
< Content-Type: application/json
{
  "url": "/segments/UUID"
  // ... other fields omitted for brevity
}

Update Segment
POST /segments/UUID
> Content-Type: application/json
{
  "name": "Segment 2",
  "query": "some query updated",
  "rebuildFrequency": "WEEKLY" // HOURLY / DAILY / WEEKLY / MONTHLY
}
< 200
< Content-Type: application/json
{
  "url": "/segments/UUID"
  // ... other fields omitted for brevity
}

Delete Segment
DELETE /segments/UUID
< 204


--
User Resources
The following is a section of resources related to Users
--

Get User
GET /users/UUID[?expand=properties]
< 200
< Content-Type: application/json
{
  "url": "/users/UUID",
  "email": "louis@gmail.com",
  "uuid": "UUID",
  "properties": [
      { "url": "/user-properies/UUID" }
  ],
  "marketingDb": { "url": "/databases/UUID" },
  "dateCreated": "2012-07-01T14:22:20.029Z", // ISO 8601 Date string
  "dateUpdated": "2012-07-01T14:22:20.029Z" // ISO 8601 Date string
}

Create User
PUT /users/UUID
> Content-Type: application/json
{
  "email": "louis@gmail.com",
  "uuid": "UUID",
  "properties": [
      { "url": "/user-properies/UUID"
        // ... other fields omitted for brevity
      }
  ],
  "marketingDb": { "url": "/databases/UUID" }
}
< 201
< Content-Type: application/json
{
  "url": "/users/UUID"
  // ... other fields omitted for brevity
}

Update User
POST /users/UUID
> Content-Type: application/json
{
  "properties": [
      { "url": "/user-properies/UUID" }
  ]
}
< 200
< Content-Type: application/json
{
  "url": "/users/UUID"
  // ... other fields omitted for brevity
}

Delete User
DELETE /users/UUID
< 204

--
User Property Resources
The following is a section of resources related to User Properties
--

Get User Property
GET /user-properties/UUID
< 200
< Content-Type: application/json
{
  "url": "/user-property/UUID",
  "name": "Age",
  "value": "32", // TODO Understand if we need to manage data type here
  "securityLevel": 2,
  "user": { "url": "/users/UUID" },
  "dateCreated": "2012-07-01T14:22:20.029Z", // ISO 8601 Date string
  "dateUpdated": "2012-07-01T14:22:20.029Z" // ISO 8601 Date string
}

Delete User Property
DELETE /user-properties/UUID
< 204

--
User Segment Membership Resources
The following is a section of resources related to User Segment Memberships
--

List users belonging to Segment (Segment Memberships)
GET /segment-memberships?segment=UUID
< 200
< Content-Type: application/json
{
  "url": "/segment-memberships?segment=UUID",
  "offset": 0,
  "limit": 50,
  "first": {"url": "/segment-memberships?segment=UUID&offset=0"},
  "prev": null,
  "next": {"url": "/segment-memberships?segment=UUID&offset=50"},
  "last": {"url": "/segment-memberships?segment=UUID&offset=100"},
  "items": [
{
  "url": "/segment-memberships?user=UUID&segment=UUID",
  "user": { 
    "url": "/users/UUID" 
    // ... other fields omitted for brevity
  },
  "segment": { 
    "url": "/segments/UUID" 
    // ... other fields omitted for brevity
    }
}
]}

Create new Segment Membership
PUT /segment-memberships
> Content-Type: application/json
{
  "user": { "url": "/users/UUID" },
  "segment": { "url": "/segments/UUID" }
}
< 201
< Content-Type: application/json
{
  "url": "/segment-memberships?user=UUID&segment=UUID"
  // ... other fields omitted for brevity
}

Delete Segment Membership
DELETE /segment-memberships?user=UUID&segment=UUID
< 204


--
Segment Rebuild Request Resources
The following is a section of resources related to Segment Rebuild Requests
--

Get Segment Rebuild Request
GET /segment-rebuild-requests/UUID
< 200
< Content-Type: application/json
{
  "url": "/segment-rebuild-requests/UUID",
  "status": "SCHEDULED", // SCHEDULED / IN_PROGRESS / COMPLETE / FAILURE
  "segment": { "url": "/segments/UUID" },
  "message": null, // Used for FAILURE requests
  "dateStarted": null, // ISO 8601 Date string
  "dateFinished": null, // ISO 8601 Date string
  "dateCreated": "2012-07-01T14:22:20.029Z", // ISO 8601 Date string
  "dateUpdated": "2012-07-01T14:22:20.029Z" // ISO 8601 Date string
}

List Segment Rebuild Requests that belong to this Manager
GET /segment-rebuild-requests
< 200
< Content-Type: application/json
{
  "url": "/segment-rebuild-requests",
  "offset": 0,
  "limit": 50,
  "first": {"url": "/segment-rebuild-requests?offset=0"},
  "prev": null,
  "next": {"url": "/segment-rebuild-requests?offset=50"},
  "last": {"url": "/segment-rebuild-requests?offset=100"},
  "items": [
{
  "url": "/segment-rebuild-requests/UUID"
  // ... other fields omitted for brevity
}
]}

Create new Segment Rebuild Request
PUT /segment-rebuild-requests/UUID
> Content-Type: application/json
{
  "segment": { "url": "/segments/UUID" }
}
< 201
< Content-Type: application/json
{
  "url": "/segment-rebuild-requests/UUID"
  // ... other fields omitted for brevity
}

Delete Segment Rebuild Request
DELETE /segment-rebuild-requests/UUID
< 204
