HOST: http://api.propzmedia.com/v1/

--- Propzmedia Studio v1 ---

---
Welcome to Propzmedia API v1 documentation. All comments can be written in (support [Markdown](http://daringfireball.net/projects/markdown/syntax) syntax)
---

--
Marketing Database Resources
The following is a section of resources related to Marketing Databases
--

Get Marketing Database
GET /databases/UUID
< 200
< Content-Type: application/json
{
  "url": "/databases/UUID",
  "name": "SocioMMA",
  "inChargeMgr": { // Optional
    "url": "/managers/UUID"
  },
  "dateCreated": "2012-07-01T14:22:20.029Z", // ISO 8601 Date string
  "dateUpdated": "2012-07-01T14:22:20.029Z" // ISO 8601 Date string
}

Create new Marketing Database
PUT /databases/UUID
> Content-Type: application/json
{
  "name": "SocioMMA",
  "inChargeMgr": { // Optional
    "url": "/managers/UUID"
  }
}
< 201
< Content-Type: application/json
{
  "url": "/databases/UUID"
  // ... other fields omitted for brevity
}

Update Marketing Database
POST /databases/UUID
> Content-Type: application/json
{
  "name": "SuccessoClub",
  "inChargeMgr": { // Optional
    "url": "/managers/UUID"
  }
}
< 200
< Content-Type: application/json
{
  "url": "/databases/UUID"
  // ... other fields omitted for brevity
}

Delete Marketing database
DELETE /databases/UUID
< 204



--
Credential Resources
The following is a section of resources related to Credentials
--

Get Credential
GET /credentials/UUID
< 200
< Content-Type: application/json
{
  "url": "/credentials/UUID",
  "apiKey": "UUID", // Optional
  "targetMgr": { "url": "/managers/UUID" }, // Optional
  "accessLevel": "ADMIN", // STAFF / ADMIN / WRITE / READ
  "active": true,
  "marketingDb": { "url": "/databases/UUID" },
  "type": "CONSOLE", // CONSOLE / WS
  "dateCreated": "2012-07-01T14:22:20.029Z", // ISO 8601 Date string
  "dateUpdated": "2012-07-01T14:22:20.029Z", // ISO 8601 Date string
  "validUntil": "2012-07-01T14:22:20.029Z" // ISO 8601 Date string
}

List Credentials for this Manager
GET /credentials
< 200
< Content-Type: application/json
{ 
    "url": "/credentials",
    "offset": 0,
    "limit": 50,
    "first": {"url": "/credentials?offset=0"},
    "prev": null,
    "next": {"url": "/credentials?offset=50"},
    "last": {"url": "/credentials?offset=100"},
    "items": [
{
  "url": "/credentials/UUID"
  // ... other fields omitted for brevity
}
] }

Create new Credential for given Marketing DB
PUT /credentials/UUID
> Content-Type: application/json
{
  "apiKey": "UUID", // Optional
  "apiSecret": "UUID", // Password to be encrypted. Optional
  "targetMgr": { "url": "/managers/UUID" }, // Optional
  "accessLevel": "ADMIN", // STAFF / ADMIN / WRITE / READ
  "active": true,
  "marketingDb": { "url": "/databases/UUID" },
  "type": "CONSOLE", // CONSOLE / WS
  "validUntil": "2012-07-01T14:22:20.029Z" // ISO 8601 Date string
}
< 201
< Content-Type: application/json
{
  "url": "/credentials/UUID"
  // ... other fields omitted for brevity
}

Update Credential
POST /credentials/UUID
> Content-Type: application/json
{
  "apiSecret": "UUID", // Password to be encrypted. Optional
  "accessLevel": "WRITE", // STAFF / ADMIN / WRITE / READ
  "active": false,
  "type": "WS", // CONSOLE / WS
  "validUntil": "2012-07-01T14:22:20.029Z" // ISO 8601 Date string
}
< 200
< Content-Type: application/json
{
  "url": "/credentials/UUID"
  // ... other fields omitted for brevity
}

Delete credentialb
DELETE /credentials/UUID
< 204



--
Manager Resources
The following is a section of resources related to Managers
--

Get Manager
GET /managers/UUID
< 200
< Content-Type: application/json
{
  "url": "/managers/UUID",
  "username": "john", 
  "firstName": "John",
  "lastName": "Smith",
  "dateCreated": "2012-07-01T14:22:20.029Z", // ISO 8601 Date string
  "dateUpdated": "2012-07-01T14:22:20.029Z" // ISO 8601 Date string
}

Create new Manager. This function is used by SignUp module only.
PUT /managers/UUID
> Content-Type: application/json
{
  "username": "john", 
  "firstName": "John",
  "lastName": "Smith",
  "password": "UUID", // Password to be encrypted. Optional
}
< 201
< Content-Type: application/json
{
  "url": "/managers/UUID"
  // ... other fields omitted for brevity
}

Update Manager
POST /managers/UUID
> Content-Type: application/json
{
  "firstName": "Mark",
  "lastName": "Twain",
  "password": "UUID", // Password to be encrypted. Optional
}
< 200
< Content-Type: application/json
{
  "url": "/managers/UUID"
  // ... other fields omitted for brevity
}



--
Manager Invitation Resources
The following is a section of resources related to Manager Invitations
--

Get Manager Invitation
GET /manager-invitations/UUID
< 200
< Content-Type: application/json
{
  "url": "/manager-invitations/UUID",
  "email": "john@gmail.com",
  "active": true,
  "sendStatus": "SENT", // NOT_SENT / SENT / FAILURE
  "targetMgr": null, // If null - invitation has not been utilized
  "dateCreated": "2012-07-01T14:22:20.029Z", // ISO 8601 Date string
  "dateUpdated": "2012-07-01T14:22:20.029Z", // ISO 8601 Date string
  "validUntil": "2012-07-01T14:22:20.029Z" // ISO 8601 Date string
}

List Manager Invitation created by this Manager
GET /manager-invitations
< 200
< Content-Type: application/json
{
    "url": "/manager-invitations",
    "offset": 0,
    "limit": 50,
    "first": {"url": "/manager-invitations?offset=0"},
    "prev": null,
    "next": {"url": "/manager-invitations?offset=50"},
    "last": {"url": "/manager-invitations?offset=100"},
    "items": [
{
  "url": "/manager-invitations/UUID"
  // ... other fields omitted for brevity
}
]}

Create new Manager Invitation
PUT /manager-invitations/UUID
> Content-Type: application/json
{
  "email": "john@gmail.com"
}
< 201
< Content-Type: application/json
{
  "url": "/manager-invitations/UUID"
  // ... other fields omitted for brevity
}

Update Manager Invitation
POST /manager-invitations/UUID
> Content-Type: application/json
{
  "active": false,
  "validUntil": "2012-07-01T14:22:20.029Z" // ISO 8601 Date string
}
< 200
< Content-Type: application/json
{
  "url": "/manager-invitations/UUID"
  // ... other fields omitted for brevity
}


--
Segment Resources
The following is a section of resources related to Segments
--

Get Segment
GET /segments/UUID
< 200
< Content-Type: application/json
{
  "url": "/segments/UUID",
  "name": "Segment 1",
  "query": "some query",
  "rebuildFrequency": "DAILY", // HOURLY / DAILY / WEEKLY / MONTHLY
  "marketingDb": { "url": "/databases/UUID" },
  "segmentMembership": { "url": "/segment-memberships?segment=UUID" },
  "dateCreated": "2012-07-01T14:22:20.029Z", // ISO 8601 Date string
  "dateUpdated": "2012-07-01T14:22:20.029Z" // ISO 8601 Date string
}

List Segment for specific Marketing DB
GET /segments?database=UUID
< 200
< Content-Type: application/json
{
    "url": "segments?database=UUID",
    "offset": 0,
    "limit": 50,
    "first": {"url": "/segments?database=UUID&offset=0"},
    "prev": null,
    "next": {"url": "/segments?database=UUID&offset=50"},
    "last": {"url": "/segments?database=UUID&offset=100"},
    "items": [
{
  "url": "/manager-invitations/UUID"
  // ... other fields omitted for brevity
}
]}

Create new Segment
PUT /segments/UUID
> Content-Type: application/json
{
  "name": "Segment 1",
  "query": "some query",
  "rebuildFrequency": "DAILY", // HOURLY / DAILY / WEEKLY / MONTHLY
  "marketingDb": { "url": "/databases/UUID" }
}
< 201
< Content-Type: application/json
{
  "url": "/segments/UUID"
  // ... other fields omitted for brevity
}

Update Segment
POST /segments/UUID
> Content-Type: application/json
{
  "name": "Segment 2",
  "query": "some query updated",
  "rebuildFrequency": "WEEKLY" // HOURLY / DAILY / WEEKLY / MONTHLY
}
< 200
< Content-Type: application/json
{
  "url": "/segments/UUID"
  // ... other fields omitted for brevity
}

Delete Segment
DELETE /segments/UUID
< 204


--
User Resources
The following is a section of resources related to Users
--

Get User
GET /users/UUID
< 200
< Content-Type: application/json
{
  "url": "/users/UUID",
  "email": "louis@gmail.com",
  "uuid": "UUID",
  "dateCreated": "2012-07-01T14:22:20.029Z", // ISO 8601 Date string
  "dateUpdated": "2012-07-01T14:22:20.029Z" // ISO 8601 Date string
}

List Segment for specific Marketing DB
GET /segments?database=UUID
< 200
< Content-Type: application/json
{
    "url": "segments?database=UUID",
    "offset": 0,
    "limit": 50,
    "first": {"url": "/segments?database=UUID&offset=0"},
    "prev": null,
    "next": {"url": "/segments?database=UUID&offset=50"},
    "last": {"url": "/segments?database=UUID&offset=100"},
    "items": [
{
  "url": "/manager-invitations/UUID"
  // ... other fields omitted for brevity
}
]}

Create new Segment
PUT /segments/UUID
> Content-Type: application/json
{
  "name": "Segment 1",
  "query": "some query",
  "rebuildFrequency": "DAILY", // HOURLY / DAILY / WEEKLY / MONTHLY
  "marketingDb": { "url": "/databases/UUID" }
}
< 201
< Content-Type: application/json
{
  "url": "/segments/UUID"
  // ... other fields omitted for brevity
}

Update Segment
POST /segments/UUID
> Content-Type: application/json
{
  "name": "Segment 2",
  "query": "some query updated",
  "rebuildFrequency": "WEEKLY" // HOURLY / DAILY / WEEKLY / MONTHLY
}
< 200
< Content-Type: application/json
{
  "url": "/segments/UUID"
  // ... other fields omitted for brevity
}

Delete Segment
DELETE /segments/UUID
< 204


--
User Segment Membership Resources
The following is a section of resources related to User Segment Memberships
--

Get Segment Membership
GET /segment-memberships?user=UUID&segment=UUID
< 200
< Content-Type: application/json
{
  "url": "/segment-memberships/UUID",
  "user": { "url": "/users/UUID" },
  "segment": { "url": "/segments/UUID" }
}

List segment memberships
GET /segment-memberships?segment=UUID
< 200
< Content-Type: application/json
{
    "url": "/segment-memberships?segment=UUID",
    "offset": 0,
    "limit": 50,
    "first": {"url": "/segment-memberships?segment=UUID&offset=0"},
    "prev": null,
    "next": {"url": "/segment-memberships?segment=UUID&offset=50"},
    "last": {"url": "/segment-memberships?segment=UUID&offset=100"},
    "items": [
{
  "url": "/segment-memberships/UUID"
  // ... other fields omitted for brevity
}
]}


