HOST: http://api.propzmedia.com/v1/

--- Propzmedia Studio v1 ---

---
Welcome to Propzmedia API v1 documentation. All comments can be written in (support [Markdown](http://daringfireball.net/projects/markdown/syntax) syntax)
---

--
Dashboard Resources
The following is a section of resources related to Dashboard
--

Get logged-in Manager Dashboard
GET /
< 200
< Content-Type: application/x-resource+json
{
  "href": "/",
  "manager": "/managers/UUID" // Shows logged-in manager's ID
}

--
Marketing Database Resources
The following is a section of resources related to Marketing Databases
--

Get Marketing Database
GET /databases/UUID
< 200
< Content-Type: application/x-resource+json
{
  "href": "/databases/UUID",
  "name": "SocioMMA",
  "inChargeMgr": { "href": "/managers/UUID" },
  "dateCreated": "2012-07-01T14:22:20.029Z", // ISO 8601 Date string
  "dateUpdated": "2012-07-01T14:22:20.029Z" // ISO 8601 Date string
}

Create new Marketing Database
PUT /databases/UUID
> Content-Type: application/json
{
  "name": "SocioMMA",
  "inChargeMgr": { "href": "/managers/UUID" }
}
< 201
< Content-Type: application/x-resource+json
{
  "href": "/databases/UUID"
  // ... other fields omitted for brevity
}

Update Marketing Database
POST /databases/UUID
> Content-Type: application/json
{
  "name": "SuccessoClub",
  "inChargeMgr": { // Optional
  "href": "/managers/UUID"
  }
}
< 200
< Content-Type: application/x-resource+json
{
  "href": "/databases/UUID"
  // ... other fields omitted for brevity
}

Delete Marketing database
DELETE /databases/UUID
< 204



--
Credential Resources
The following is a section of resources related to Credentials
--

Get Credential
GET /credentials/UUID
< 200
< Content-Type: application/x-resource+json
{
  "href": "/credentials/UUID",
  "apiKey": "UUID", // May be null if "targetMgr" present
  "targetMgr": { "href": "/managers/UUID" }, // May be null if "apiKey"/"apiSecret" present
  "targetMgrInvitation": { "href": "manager-invitations/UUID"} // Coupled with "targetMgr"
  "accessLevel": "ADMIN", // STAFF / ADMIN / WRITE / READ
  "active": true,
  "db": { "href": "/databases/UUID" },
  "type": "CONSOLE", // CONSOLE / WS
  "dateCreated": "2012-07-01T14:22:20.029Z", // ISO 8601 Date string
  "dateUpdated": "2012-07-01T14:22:20.029Z", // ISO 8601 Date string
  "validUntil": "2012-07-01T14:22:20.029Z" // ISO 8601 Date string
}

List Credentials for specific Manager
GET /credentials?targetMgr=UUID
< 200
< Content-Type: application/x-collection+json
{ 
  "href": "/credentials",
  "offset": 0,
  "limit": 50,
  "first": {"href": "/credentials?offset=0"},
  "prev": null,
  "next": {"href": "/credentials?offset=50"},
  "last": {"href": "/credentials?offset=100"},
  "items": [
{
  "href": "/credentials/UUID"
  // ... other fields omitted for brevity
}
] }

Create new Credential for given Marketing DB
PUT /credentials/UUID
> Content-Type: application/json
{
  "apiKey": "UUID", // Optional
  "apiSecret": "NEW_PASSWORD", // Password to be encrypted. Optional
  "targetMgr": { "href": "/managers/UUID" }, // May be null if "apiKey"/"apiSecret" present
  "targetMgrInvitation": { "href": "manager-invitations/UUID" } // Coupled with "targetMgr"
  "accessLevel": "ADMIN", // STAFF / ADMIN / WRITE / READ
  "active": true,
  "db": { "href": "/databases/UUID" },
  "type": "CONSOLE", // CONSOLE / WS
  "validUntil": "2012-07-01T14:22:20.029Z" // ISO 8601 Date string
}
< 201
< Content-Type: application/x-resource+json
{
  "href": "/credentials/UUID"
  // ... other fields omitted for brevity
}

Update Credential
POST /credentials/UUID
> Content-Type: application/json
{
  "apiSecret": "NEW_PASSWORD", // Password to be encrypted. Optional
  "accessLevel": "WRITE", // STAFF / ADMIN / WRITE / READ
  "active": false,
  "type": "WS", // CONSOLE / WS
  "validUntil": "2012-07-01T14:22:20.029Z" // ISO 8601 Date string
}
< 200
< Content-Type: application/x-resource+json
{
  "href": "/credentials/UUID"
  // ... other fields omitted for brevity
}

Delete credentialb
DELETE /credentials/UUID
< 204



--
Manager Resources
The following is a section of resources related to Managers
--

Get Manager
GET /managers/UUID[?expand=credentials.db]
< 200
< Content-Type: application/x-resource+json
{
  "href": "/managers/UUID",
  "username": "john", 
  "email": "john@gmail.com",
  "phone": "+550001112222",
  "firstName": "John",
  "lastName": "Smith",
  "company": "Propzmedia",
  "status": "ACTIVE", // ACTIVE / AWAITING_CONFIRMATION
  "emailConfirmation": { "href": "/managers/UUID/confirmation/email" },
  "managerInvitations" : { "href": "/manager-invitations?creatorMgr=UUID" },
  "credentials": { "href": "/credentials?targetMgr=UUID" },
  "dateCreated": "2012-07-01T14:22:20.029Z", // ISO 8601 Date string
  "dateUpdated": "2012-07-01T14:22:20.029Z" // ISO 8601 Date string
}

Create new Manager. This function is used by SignUp module only.
PUT /managers/UUID
> Content-Type: application/json
{
  "username": "john", 
  "email": "john@gmail.com",
  "phone": "+550001112222",
  "firstName": "John",
  "lastName": "Smith",
  "company": "Propzmedia",
  "password": "NEW_PASSWORD", // Password to be encrypted. Optional
}
< 201
< Content-Type: application/x-resource+json
{
  "href": "/managers/UUID"
  // ... other fields omitted for brevity
}

Update Manager
POST /managers/UUID
> Content-Type: application/json
{
  "firstName": "Mark",
  "lastName": "Twain",
  "password": "NEW_PASSWORD", // Password to be encrypted. Optional
}
< 200
< Content-Type: application/x-resource+json
{
  "href": "/managers/UUID"
  // ... other fields omitted for brevity
}

Get Email Confirmation
GET /managers/UUID/confirmation/email
< 200
< Content-Type: application/x-resource+json
{
  "href": "/managers/UUID/confirmation/email",
  "manager": "/managers/UUID",
  "status": "CONFIRMED", // AWAITING / CONFIRMED
  "token": "UUID",
  "dateCreated": "2012-07-01T14:22:20.029Z", // ISO 8601 Date string
  "dateUpdated": "2012-07-01T14:22:20.029Z" // ISO 8601 Date string
}

Update Email Confirmation
POST /managers/UUID/confirmation/email
> Content-Type: application/json
{
  "status": "CONFIRMED"
}
< 200
< Content-Type: application/x-resource+json
{
  "href": "/managers/UUID/confirmation/email"
  // ... other fields omitted for brevity
}

--
Manager Invitation Resources
The following is a section of resources related to Manager Invitations
--

List Manager Invitation created by certain Manager
GET /manager-invitations?creatorMgr=UUID
< 200
< Content-Type: application/x-collection+json
{
  "href": "/manager-invitations",
  "offset": 0,
  "limit": 50,
  "first": {"href": "/manager-invitations?creatorMgr=UUID&offset=0"},
  "prev": null,
  "next": {"href": "/manager-invitations?creatorMgr=UUID&offset=50"},
  "last": {"href": "/manager-invitations?creatorMgr=UUID&offset=100"},
  "items": [
{
  "href": "/manager-invitations/UUID"
  // ... other fields omitted for brevity
}
]}

Get Manager Invitation
GET /manager-invitations/UUID
< 200
< Content-Type: application/x-resource+json
{
  "href": "/manager-invitations/UUID",
  "email": "john@gmail.com",
  "token": "UUID",
  "active": true,
  "sendStatus": "SENT", // NOT_SENT / SENT / FAILURE
  "targetMgr": null, // If null - invitation has not been utilized
  "creatorMgr": { "href": "/managers/UUID" },
  "dateCreated": "2012-07-01T14:22:20.029Z", // ISO 8601 Date string
  "dateUpdated": "2012-07-01T14:22:20.029Z", // ISO 8601 Date string
  "validUntil": "2012-07-01T14:22:20.029Z" // ISO 8601 Date string
}

Create new Manager Invitation
PUT /manager-invitations/UUID
> Content-Type: application/json
{
  "email": "john@gmail.com"
}
< 201
< Content-Type: application/x-resource+json
{
  "href": "/manager-invitations/UUID"
  // ... other fields omitted for brevity
}

Update Manager Invitation
POST /manager-invitations/UUID
> Content-Type: application/json
{
  "active": false,
  "validUntil": "2012-07-01T14:22:20.029Z" // ISO 8601 Date string
}
< 200
< Content-Type: application/x-resource+json
{
  "href": "/manager-invitations/UUID"
  // ... other fields omitted for brevity
}


--
Segment Resources
The following is a section of resources related to Segments
--

Get Segment
GET /segments/UUID
< 200
< Content-Type: application/x-resource+json
{
  "href": "/segments/UUID",
  "name": "Segment 1",
  "query": "some query",
  "rebuildFrequency": "DAILY", // HOURLY / DAILY / WEEKLY / MONTHLY
  "db": { "href": "/databases/UUID" },
  "segmentMembership": { "href": "/segment-memberships?segment=UUID" },
  "dateCreated": "2012-07-01T14:22:20.029Z", // ISO 8601 Date string
  "dateUpdated": "2012-07-01T14:22:20.029Z" // ISO 8601 Date string
}

List Segment for specific Marketing DB
GET /segments?database=UUID
< 200
< Content-Type: application/x-collection+json
{
  "href": "segments?database=UUID",
  "offset": 0,
  "limit": 50,
  "first": {"href": "/segments?database=UUID&offset=0"},
  "prev": null,
  "next": {"href": "/segments?database=UUID&offset=50"},
  "last": {"href": "/segments?database=UUID&offset=100"},
  "items": [
{
  "href": "/manager-invitations/UUID"
  // ... other fields omitted for brevity
}
]}

Create new Segment
PUT /segments/UUID
> Content-Type: application/json
{
  "name": "Segment 1",
  "query": "some query",
  "rebuildFrequency": "DAILY", // HOURLY / DAILY / WEEKLY / MONTHLY
  "db": { "href": "/databases/UUID" }
}
< 201
< Content-Type: application/x-resource+json
{
  "href": "/segments/UUID"
  // ... other fields omitted for brevity
}

Update Segment
POST /segments/UUID
> Content-Type: application/json
{
  "name": "Segment 2",
  "query": "some query updated",
  "rebuildFrequency": "WEEKLY" // HOURLY / DAILY / WEEKLY / MONTHLY
}
< 200
< Content-Type: application/x-resource+json
{
  "href": "/segments/UUID"
  // ... other fields omitted for brevity
}

Delete Segment
DELETE /segments/UUID
< 204


--
User Resources
The following is a section of resources related to Users
--

Get User
GET /users/UUID[?expand=properties]
< 200
< Content-Type: application/x-resource+json
{
  "href": "/users/UUID",
  "email": "louis@gmail.com",
  "uuid": "UUID",
  "properties": [
      { "href": "/user-properies/UUID" }
  ],
  "db": { "href": "/databases/UUID" },
  "dateCreated": "2012-07-01T14:22:20.029Z", // ISO 8601 Date string
  "dateUpdated": "2012-07-01T14:22:20.029Z" // ISO 8601 Date string
}

Create User
PUT /users/UUID
> Content-Type: application/json
{
  "email": "louis@gmail.com",
  "uuid": "UUID",
  "properties": [
      { "href": "/user-properies/UUID"
        // ... other fields omitted for brevity
      }
  ],
  "db": { "href": "/databases/UUID" }
}
< 201
< Content-Type: application/x-resource+json
{
  "href": "/users/UUID"
  // ... other fields omitted for brevity
}

Update User
POST /users/UUID
> Content-Type: application/json
{
  "properties": [
      { "href": "/user-properies/UUID" }
  ]
}
< 200
< Content-Type: application/x-resource+json
{
  "href": "/users/UUID"
  // ... other fields omitted for brevity
}

Delete User
DELETE /users/UUID
< 204

--
User Property Resources
The following is a section of resources related to User Properties
--

Get User Property
GET /user-properties/UUID
< 200
< Content-Type: application/x-resource+json
{
  "href": "/user-property/UUID",
  "name": "Age",
  "value": "32", // TODO Understand if we need to manage data type here
  "securityLevel": "PUBLIC", // PUBLIC / FRIEND / PRIVATE / COMPANY
  "user": { "href": "/users/UUID" },
  "dateCreated": "2012-07-01T14:22:20.029Z", // ISO 8601 Date string
  "dateUpdated": "2012-07-01T14:22:20.029Z" // ISO 8601 Date string
}

Delete User Property
DELETE /user-properties/UUID
< 204

--
User Segment Membership Resources
The following is a section of resources related to User Segment Memberships
--

List users belonging to Segment (Segment Memberships)
GET /segment-memberships?segment=UUID
< 200
< Content-Type: application/x-collection+json
{
  "href": "/segment-memberships?segment=UUID",
  "offset": 0,
  "limit": 50,
  "first": {"href": "/segment-memberships?segment=UUID&offset=0"},
  "prev": null,
  "next": {"href": "/segment-memberships?segment=UUID&offset=50"},
  "last": {"href": "/segment-memberships?segment=UUID&offset=100"},
  "items": [
{
  "href": "/segment-memberships?user=UUID&segment=UUID",
  "user": { 
    "href": "/users/UUID" 
    // ... other fields omitted for brevity
  },
  "segment": { 
    "href": "/segments/UUID" 
    // ... other fields omitted for brevity
    }
}
]}

Create new Segment Membership
PUT /segment-memberships
> Content-Type: application/json
{
  "user": { "href": "/users/UUID" },
  "segment": { "href": "/segments/UUID" }
}
< 201
< Content-Type: application/x-resource+json
{
  "href": "/segment-memberships?user=UUID&segment=UUID"
  // ... other fields omitted for brevity
}

Delete Segment Membership
DELETE /segment-memberships?user=UUID&segment=UUID
< 204

--
Executor Status Resources
The following is a section of resources related to Executor Statuses
--

Get Executor Status
GET /executor-status/UUID
< 200
< Content-Type: application/x-resource+json
{
  "href": "/executor-status/UUID",
  "status": "SCHEDULED", // SCHEDULED / IN_PROGRESS / COMPLETE
  "request": { "href": "/.../UUID" }, // Reference to request that initiated this execution.
  "dateStarted": null, // ISO 8601 Date string
  "dateFinished": null, // ISO 8601 Date string
  "progress": 0, // Will be updated time to time for client polling
  "goal": 0, // Will be updated when job starts
  "response": { 
      {
        "href": "/executor-status/UUID/response",
        "messageItems": {
            "messages": { "href": "/executor-status/UUID/response/messages;message" },
            "warnings": { "href": "/executor-status/UUID/response/messages;warning" },
            "errors": { "href": "/executor-status/UUID/response/messages;error" }
        },
        "dateCreated": "2012-07-01T14:22:20.029Z", // ISO 8601 Date string
        "dateUpdated": "2012-07-01T14:22:20.029Z" // ISO 8601 Date string
        }
    } 
  "dateCreated": "2012-07-01T14:22:20.029Z", // ISO 8601 Date string
  "dateUpdated": "2012-07-01T14:22:20.029Z" // ISO 8601 Date string
}

List Executor Status Response Messages
GET /executor-status/UUID/response/messages[;(message|warning|error)]
< 200
< Content-Type: application/x-collection+json
{
  "href": "/executor-status/UUID/response/messages[;(message|warning|error)]",
  "offset": 0,
  "limit": 50,
  "first": {"href": "/executor-status/UUID/response/[;(message|warning|error)]?offset=0"},
  "prev": null,
  "next": {"href": "/executor-status/UUID/response/[;(message|warning|error)]?offset=50"},
  "last": {"href": "/executor-status/UUID/response/[;(message|warning|error)]?offset=100"},
  "items": [
      {
    "href": "/executor-status/UUID/response/[;(message|warning|error)]/INDEX",
    "type": "ERROR", // MESSAGE / WARNING / ERROR
    "code": "ST001",
    "text": "Import file is too big."
}]}


--
Segment Rebuild Job Resources
The following is a section of resources related to Segment Rebuild Jobs
--

Get Segment Rebuild Job
GET /segment-rebuild-jobs/UUID
< 200
< Content-Type: application/x-resource+json
{
  "href": "/segment-rebuild-jobs/UUID",
  "segment": { "href": "/segments/UUID" },
  "status": { "href": "/executor-status/UUID" },
  "dateCreated": "2012-07-01T14:22:20.029Z", // ISO 8601 Date string
  "dateUpdated": "2012-07-01T14:22:20.029Z" // ISO 8601 Date string
}

List Segment Rebuild Jobs that belong to this Manager
GET /segment-rebuild-jobs
< 200
< Content-Type: application/x-collection+json
{
  "href": "/segment-rebuild-jobs",
  "offset": 0,
  "limit": 50,
  "first": {"href": "/segment-rebuild-jobs?offset=0"},
  "prev": null,
  "next": {"href": "/segment-rebuild-jobs?offset=50"},
  "last": {"href": "/segment-rebuild-jobs?offset=100"},
  "items": [
{
  "href": "/segment-rebuild-jobs/UUID"
  // ... other fields omitted for brevity
}
]}

Create new Segment Rebuild Job
PUT /segment-rebuild-jobs/UUID
> Content-Type: application/json
{
  "segment": { "href": "/segments/UUID" }
}
< 201
< Content-Type: application/x-resource+json
{
  "href": "/segment-rebuild-jobs/UUID"
  // ... other fields omitted for brevity
}

Delete Segment Rebuild Job
DELETE /segment-rebuild-jobs/UUID
< 204
